# Generated by Django 4.1.3 on 2022-11-26 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_tag_article_referring_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='relationship',
            field=models.ManyToManyField(blank=True, related_name='Тег', to='blog.article'),
        ),
    ]
