# Generated by Django 4.1.3 on 2023-01-03 14:56

from django.db import migrations
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Зображення товару', 'verbose_name_plural': 'Зображення товару'},
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default=django.utils.timezone.now, upload_to='catalogue/product/', verbose_name='Зображеня'),
            preserve_default=False,
        ),
    ]
